language: python
python:
  - "2.7"
#  - "3.3"
#  - "3.4"
  - "3.5"
env:
  global:
    - DJANGO_SETTINGS_MODULE="test_app.settings_travis"
    - PYTHONPATH="/home/travis/build/kbussell/django-jsonfield-compat"
    - TRAVIS_BUILD=true
  matrix:
    - DJANGO_VERSION=1.9.* DB=postgresql
    - DJANGO_VERSION=1.10.* DB=postgresql
    - DJANGO_VERSION=1.9.* DB=mysql
    - DJANGO_VERSION=1.10.* DB=mysql

dist: trusty

addons:
    postgresql: "9.5"

services:
    - postgresql
    - mysql-server-5.5

install:
  - "pip install -q Django==$DJANGO_VERSION"
  - "pip install q -r requirements.txt"
  - "pip install coveralls"

before_script:
  - sh -c "if [ '$DB' = 'postgresql' ]; then psql -c 'DROP DATABASE IF EXISTS travisdb;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'postgresql' ]; then psql -c 'CREATE DATABASE travisdb;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'DROP DATABASE IF EXISTS travisdb;'; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE travisdb;'; fi"

script:
  - coverage run --source=jsonfield_compat tests/runtests.py

after_success:
  coveralls
